accent = "#C3A87C"
cursor = "#E5DAC9"
foreground = "#E5DAC9"
background = "#1B191B"
selection_foreground = "#1B191B"
selection_background = "#C3A87C"

color0 = "#25211F"
color1 = "#89644C"
color2 = "#8A765C"
color3 = "#C3A87C"
color4 = "#6D5E4B"
color5 = "#82663E"
color6 = "#7A6F5E"
color7 = "#D4C8B7"
color8 = "#443B31"
color9 = "#A68D65"
color10 = "#A89375"
color11 = "#E3C49F"
color12 = "#98866C"
color13 = "#B7A68E"
color14 = "#AA9F90"
color15 = "#E5DAC9"
