# Vigil — warm ochre border fading to deep umber
$activeBorderColor = rgba(C3A87Ccc) rgba(443B31cc) 45deg
$inactiveBorderColor = rgba(25211F66)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor

    groupbar {
        text_color = rgb(E5DAC9)
        text_color_inactive = rgba(E5DAC960)
        col.active = rgba(C3A87C30)
        col.inactive = rgba(25211F30)
    }
}
